name: Workflow-1

on:
  push: 

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --save-dev jest supertest

      - name: test
        run: npm test
