name: Workflow-3

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: test
        run: npm test

      - name: starting the app
        run: npm start
