name: Workflow-3

on:
  workflow_dispatch:

jobs:
  job-1:
    name: Print Messages Job
    runs-on: ubuntu-24.04

    steps:
      - name: Print Welcome Message
        run: |
          echo "Hello all from GitHub Actions"

      - name: Print Thank You Message
        run: |
          echo "Thanks for using GitHub Actions"
