name: Workflow-5

on:
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Print first message
        run: echo "Hello everyone! Welcome to GitHub Actions!"

      - name: Print second message
        run: echo "Thank you for using GitHub Actions! Happy Learning!"
